services:
    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postworthee
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    minio:
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000" # S3 API port
            - "9001:9001" # Console UI
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio-data:/data
        restart: always

volumes:
    pgdata:
    minio-data:
